# Generated by Django 3.2.12 on 2024-06-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_resources', models.CharField(max_length=20)),
                ('tables', models.PositiveSmallIntegerField()),
                ('chairs', models.CharField(max_length=20)),
                ('room_number', models.PositiveSmallIntegerField()),
                ('assignment', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('class_id', models.PositiveSmallIntegerField()),
                ('teacher', models.CharField(max_length=20)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('learning_hours', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
