# Generated by Django 3.2.12 on 2024-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=20)),
                ('course_score', models.PositiveSmallIntegerField()),
                ('coure_interest', models.CharField(max_length=20)),
                ('course_requirement', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('professor_attributes', models.CharField(max_length=20)),
                ('course_hour', models.PositiveSmallIntegerField()),
                ('year_introduced', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
